-- 表的数据: xt_region --
INSERT INTO `xt_region` VALUES ('1','0','中国','0','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('2','1','北京','1','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('3','1','安徽','1','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('4','1','福建','1','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('5','1','甘肃','1','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('6','1','广东','1','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('7','1','广西','1','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('8','1','贵州','1','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('9','1','海南','1','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('10','1','河北','1','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('11','1','河南','1','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('12','1','黑龙江','1','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('13','1','湖北','1','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('14','1','湖南','1','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('15','1','吉林','1','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('16','1','江苏','1','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('17','1','江西','1','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('18','1','辽宁','1','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('19','1','内蒙古','1','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('20','1','宁夏','1','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('21','1','青海','1','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('22','1','山东','1','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('23','1','山西','1','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('24','1','陕西','1','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('25','1','上海','1','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('26','1','四川','1','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('27','1','天津','1','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('28','1','西藏','1','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('29','1','新疆','1','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('30','1','云南','1','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('31','1','浙江','1','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('32','1','重庆','1','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('33','1','香港','1','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('34','1','澳门','1','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('35','1','台湾','1','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('36','3','安庆','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('37','3','蚌埠','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('38','3','巢湖','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('39','3','池州','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('40','3','滁州','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('41','3','阜阳','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('42','3','淮北','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('43','3','淮南','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('44','3','黄山','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('45','3','六安','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('46','3','马鞍山','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('47','3','宿州','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('48','3','铜陵','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('49','3','芜湖','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('50','3','宣城','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('51','3','亳州','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('52','2','北京','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('53','4','福州','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('54','4','龙岩','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('55','4','南平','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('56','4','宁德','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('57','4','莆田','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('58','4','泉州','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('59','4','三明','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('60','4','厦门','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('61','4','漳州','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('62','5','兰州','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('63','5','白银','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('64','5','定西','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('65','5','甘南','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('66','5','嘉峪关','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('67','5','金昌','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('68','5','酒泉','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('69','5','临夏','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('70','5','陇南','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('71','5','平凉','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('72','5','庆阳','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('73','5','天水','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('74','5','武威','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('75','5','张掖','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('76','6','广州','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('77','6','深圳','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('78','6','潮州','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('79','6','东莞','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('80','6','佛山','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('81','6','河源','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('82','6','惠州','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('83','6','江门','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('84','6','揭阳','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('85','6','茂名','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('86','6','梅州','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('87','6','清远','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('88','6','汕头','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('89','6','汕尾','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('90','6','韶关','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('91','6','阳江','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('92','6','云浮','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('93','6','湛江','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('94','6','肇庆','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('95','6','中山','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('96','6','珠海','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('97','7','南宁','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('98','7','桂林','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('99','7','百色','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('100','7','北海','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('101','7','崇左','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('102','7','防城港','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('103','7','贵港','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('104','7','河池','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('105','7','贺州','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('106','7','来宾','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('107','7','柳州','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('108','7','钦州','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('109','7','梧州','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('110','7','玉林','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('111','8','贵阳','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('112','8','安顺','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('113','8','毕节','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('114','8','六盘水','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('115','8','黔东南','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('116','8','黔南','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('117','8','黔西南','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('118','8','铜仁','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('119','8','遵义','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('120','9','海口','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('121','9','三亚','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('122','9','白沙','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('123','9','保亭','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('124','9','昌江','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('125','9','澄迈县','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('126','9','定安县','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('127','9','东方','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('128','9','乐东','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('129','9','临高县','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('130','9','陵水','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('131','9','琼海','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('132','9','琼中','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('133','9','屯昌县','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('134','9','万宁','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('135','9','文昌','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('136','9','五指山','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('137','9','儋州','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('138','10','石家庄','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('139','10','保定','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('140','10','沧州','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('141','10','承德','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('142','10','邯郸','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('143','10','衡水','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('144','10','廊坊','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('145','10','秦皇岛','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('146','10','唐山','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('147','10','邢台','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('148','10','张家口','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('149','11','郑州','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('150','11','洛阳','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('151','11','开封','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('152','11','安阳','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('153','11','鹤壁','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('154','11','济源','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('155','11','焦作','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('156','11','南阳','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('157','11','平顶山','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('158','11','三门峡','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('159','11','商丘','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('160','11','新乡','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('161','11','信阳','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('162','11','许昌','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('163','11','周口','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('164','11','驻马店','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('165','11','漯河','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('166','11','濮阳','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('167','12','哈尔滨','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('168','12','大庆','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('169','12','大兴安岭','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('170','12','鹤岗','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('171','12','黑河','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('172','12','鸡西','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('173','12','佳木斯','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('174','12','牡丹江','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('175','12','七台河','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('176','12','齐齐哈尔','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('177','12','双鸭山','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('178','12','绥化','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('179','12','伊春','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('180','13','武汉','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('181','13','仙桃','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('182','13','鄂州','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('183','13','黄冈','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('184','13','黄石','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('185','13','荆门','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('186','13','荆州','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('187','13','潜江','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('188','13','神农架林区','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('189','13','十堰','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('190','13','随州','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('191','13','天门','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('192','13','咸宁','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('193','13','襄樊','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('194','13','孝感','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('195','13','宜昌','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('196','13','恩施','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('197','14','长沙','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('198','14','张家界','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('199','14','常德','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('200','14','郴州','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('201','14','衡阳','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('202','14','怀化','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('203','14','娄底','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('204','14','邵阳','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('205','14','湘潭','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('206','14','湘西','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('207','14','益阳','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('208','14','永州','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('209','14','岳阳','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('210','14','株洲','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('211','15','长春','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('212','15','吉林','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('213','15','白城','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('214','15','白山','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('215','15','辽源','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('216','15','四平','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('217','15','松原','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('218','15','通化','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('219','15','延边','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('220','16','南京','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('221','16','苏州','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('222','16','无锡','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('223','16','常州','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('224','16','淮安','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('225','16','连云港','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('226','16','南通','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('227','16','宿迁','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('228','16','泰州','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('229','16','徐州','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('230','16','盐城','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('231','16','扬州','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('232','16','镇江','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('233','17','南昌','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('234','17','抚州','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('235','17','赣州','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('236','17','吉安','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('237','17','景德镇','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('238','17','九江','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('239','17','萍乡','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('240','17','上饶','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('241','17','新余','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('242','17','宜春','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('243','17','鹰潭','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('244','18','沈阳','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('245','18','大连','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('246','18','鞍山','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('247','18','本溪','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('248','18','朝阳','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('249','18','丹东','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('250','18','抚顺','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('251','18','阜新','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('252','18','葫芦岛','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('253','18','锦州','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('254','18','辽阳','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('255','18','盘锦','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('256','18','铁岭','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('257','18','营口','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('258','19','呼和浩特','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('259','19','阿拉善盟','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('260','19','巴彦淖尔盟','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('261','19','包头','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('262','19','赤峰','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('263','19','鄂尔多斯','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('264','19','呼伦贝尔','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('265','19','通辽','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('266','19','乌海','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('267','19','乌兰察布市','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('268','19','锡林郭勒盟','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('269','19','兴安盟','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('270','20','银川','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('271','20','固原','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('272','20','石嘴山','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('273','20','吴忠','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('274','20','中卫','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('275','21','西宁','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('276','21','果洛','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('277','21','海北','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('278','21','海东','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('279','21','海南','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('280','21','海西','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('281','21','黄南','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('282','21','玉树','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('283','22','济南','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('284','22','青岛','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('285','22','滨州','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('286','22','德州','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('287','22','东营','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('288','22','菏泽','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('289','22','济宁','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('290','22','莱芜','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('291','22','聊城','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('292','22','临沂','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('293','22','日照','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('294','22','泰安','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('295','22','威海','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('296','22','潍坊','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('297','22','烟台','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('298','22','枣庄','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('299','22','淄博','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('300','23','太原','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('301','23','长治','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('302','23','大同','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('303','23','晋城','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('304','23','晋中','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('305','23','临汾','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('306','23','吕梁','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('307','23','朔州','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('308','23','忻州','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('309','23','阳泉','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('310','23','运城','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('311','24','西安','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('312','24','安康','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('313','24','宝鸡','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('314','24','汉中','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('315','24','商洛','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('316','24','铜川','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('317','24','渭南','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('318','24','咸阳','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('319','24','延安','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('320','24','榆林','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('321','25','上海','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('322','26','成都','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('323','26','绵阳','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('324','26','阿坝','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('325','26','巴中','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('326','26','达州','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('327','26','德阳','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('328','26','甘孜','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('329','26','广安','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('330','26','广元','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('331','26','乐山','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('332','26','凉山','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('333','26','眉山','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('334','26','南充','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('335','26','内江','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('336','26','攀枝花','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('337','26','遂宁','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('338','26','雅安','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('339','26','宜宾','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('340','26','资阳','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('341','26','自贡','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('342','26','泸州','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('343','27','天津','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('344','28','拉萨','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('345','28','阿里','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('346','28','昌都','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('347','28','林芝','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('348','28','那曲','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('349','28','日喀则','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('350','28','山南','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('351','29','乌鲁木齐','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('352','29','阿克苏','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('353','29','阿拉尔','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('354','29','巴音郭楞','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('355','29','博尔塔拉','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('356','29','昌吉','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('357','29','哈密','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('358','29','和田','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('359','29','喀什','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('360','29','克拉玛依','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('361','29','克孜勒苏','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('362','29','石河子','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('363','29','图木舒克','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('364','29','吐鲁番','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('365','29','五家渠','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('366','29','伊犁','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('367','30','昆明','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('368','30','怒江','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('369','30','普洱','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('370','30','丽江','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('371','30','保山','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('372','30','楚雄','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('373','30','大理','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('374','30','德宏','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('375','30','迪庆','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('376','30','红河','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('377','30','临沧','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('378','30','曲靖','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('379','30','文山','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('380','30','西双版纳','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('381','30','玉溪','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('382','30','昭通','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('383','31','杭州','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('384','31','湖州','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('385','31','嘉兴','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('386','31','金华','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('387','31','丽水','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('388','31','宁波','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('389','31','绍兴','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('390','31','台州','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('391','31','温州','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('392','31','舟山','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('393','31','衢州','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('394','32','重庆','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('395','33','香港','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('396','34','澳门','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('397','35','台湾','2','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('398','36','迎江区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('399','36','大观区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('400','36','宜秀区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('401','36','桐城市','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('402','36','怀宁县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('403','36','枞阳县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('404','36','潜山县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('405','36','太湖县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('406','36','宿松县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('407','36','望江县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('408','36','岳西县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('409','37','中市区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('410','37','东市区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('411','37','西市区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('412','37','郊区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('413','37','怀远县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('414','37','五河县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('415','37','固镇县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('416','38','居巢区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('417','38','庐江县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('418','38','无为县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('419','38','含山县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('420','38','和县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('421','39','贵池区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('422','39','东至县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('423','39','石台县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('424','39','青阳县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('425','40','琅琊区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('426','40','南谯区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('427','40','天长市','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('428','40','明光市','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('429','40','来安县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('430','40','全椒县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('431','40','定远县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('432','40','凤阳县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('433','41','蚌山区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('434','41','龙子湖区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('435','41','禹会区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('436','41','淮上区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('437','41','颍州区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('438','41','颍东区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('439','41','颍泉区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('440','41','界首市','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('441','41','临泉县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('442','41','太和县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('443','41','阜南县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('444','41','颖上县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('445','42','相山区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('446','42','杜集区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('447','42','烈山区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('448','42','濉溪县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('449','43','田家庵区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('450','43','大通区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('451','43','谢家集区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('452','43','八公山区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('453','43','潘集区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('454','43','凤台县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('455','44','屯溪区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('456','44','黄山区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('457','44','徽州区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('458','44','歙县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('459','44','休宁县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('460','44','黟县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('461','44','祁门县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('462','45','金安区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('463','45','裕安区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('464','45','寿县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('465','45','霍邱县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('466','45','舒城县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('467','45','金寨县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('468','45','霍山县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('469','46','雨山区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('470','46','花山区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('471','46','金家庄区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('472','46','当涂县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('473','47','埇桥区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('474','47','砀山县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('475','47','萧县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('476','47','灵璧县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('477','47','泗县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('478','48','铜官山区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('479','48','狮子山区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('480','48','郊区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('481','48','铜陵县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('482','49','镜湖区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('483','49','弋江区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('484','49','鸠江区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('485','49','三山区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('486','49','芜湖县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('487','49','繁昌县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('488','49','南陵县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('489','50','宣州区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('490','50','宁国市','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('491','50','郎溪县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('492','50','广德县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('493','50','泾县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('494','50','绩溪县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('495','50','旌德县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('496','51','涡阳县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('497','51','蒙城县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('498','51','利辛县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('499','51','谯城区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('500','52','东城区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('501','52','西城区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('502','52','海淀区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('503','52','朝阳区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('504','52','崇文区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('505','52','宣武区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('506','52','丰台区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('507','52','石景山区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('508','52','房山区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('509','52','门头沟区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('510','52','通州区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('511','52','顺义区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('512','52','昌平区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('513','52','怀柔区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('514','52','平谷区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('515','52','大兴区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('516','52','密云县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('517','52','延庆县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('518','53','鼓楼区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('519','53','台江区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('520','53','仓山区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('521','53','马尾区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('522','53','晋安区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('523','53','福清市','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('524','53','长乐市','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('525','53','闽侯县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('526','53','连江县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('527','53','罗源县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('528','53','闽清县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('529','53','永泰县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('530','53','平潭县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('531','54','新罗区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('532','54','漳平市','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('533','54','长汀县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('534','54','永定县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('535','54','上杭县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('536','54','武平县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('537','54','连城县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('538','55','延平区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('539','55','邵武市','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('540','55','武夷山市','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('541','55','建瓯市','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('542','55','建阳市','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('543','55','顺昌县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('544','55','浦城县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('545','55','光泽县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('546','55','松溪县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('547','55','政和县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('548','56','蕉城区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('549','56','福安市','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('550','56','福鼎市','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('551','56','霞浦县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('552','56','古田县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('553','56','屏南县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('554','56','寿宁县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('555','56','周宁县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('556','56','柘荣县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('557','57','城厢区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('558','57','涵江区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('559','57','荔城区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('560','57','秀屿区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('561','57','仙游县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('562','58','鲤城区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('563','58','丰泽区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('564','58','洛江区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('565','58','清濛开发区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('566','58','泉港区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('567','58','石狮市','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('568','58','晋江市','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('569','58','南安市','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('570','58','惠安县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('571','58','安溪县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('572','58','永春县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('573','58','德化县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('574','58','金门县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('575','59','梅列区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('576','59','三元区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('577','59','永安市','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('578','59','明溪县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('579','59','清流县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('580','59','宁化县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('581','59','大田县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('582','59','尤溪县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('583','59','沙县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('584','59','将乐县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('585','59','泰宁县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('586','59','建宁县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('587','60','思明区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('588','60','海沧区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('589','60','湖里区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('590','60','集美区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('591','60','同安区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('592','60','翔安区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('593','61','芗城区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('594','61','龙文区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('595','61','龙海市','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('596','61','云霄县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('597','61','漳浦县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('598','61','诏安县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('599','61','长泰县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('600','61','东山县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('601','61','南靖县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('602','61','平和县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('603','61','华安县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('604','62','皋兰县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('605','62','城关区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('606','62','七里河区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('607','62','西固区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('608','62','安宁区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('609','62','红古区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('610','62','永登县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('611','62','榆中县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('612','63','白银区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('613','63','平川区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('614','63','会宁县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('615','63','景泰县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('616','63','靖远县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('617','64','临洮县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('618','64','陇西县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('619','64','通渭县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('620','64','渭源县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('621','64','漳县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('622','64','岷县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('623','64','安定区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('624','64','安定区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('625','65','合作市','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('626','65','临潭县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('627','65','卓尼县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('628','65','舟曲县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('629','65','迭部县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('630','65','玛曲县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('631','65','碌曲县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('632','65','夏河县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('633','66','嘉峪关市','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('634','67','金川区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('635','67','永昌县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('636','68','肃州区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('637','68','玉门市','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('638','68','敦煌市','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('639','68','金塔县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('640','68','瓜州县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('641','68','肃北','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('642','68','阿克塞','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('643','69','临夏市','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('644','69','临夏县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('645','69','康乐县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('646','69','永靖县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('647','69','广河县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('648','69','和政县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('649','69','东乡族自治县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('650','69','积石山','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('651','70','成县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('652','70','徽县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('653','70','康县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('654','70','礼县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('655','70','两当县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('656','70','文县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('657','70','西和县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('658','70','宕昌县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('659','70','武都区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('660','71','崇信县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('661','71','华亭县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('662','71','静宁县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('663','71','灵台县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('664','71','崆峒区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('665','71','庄浪县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('666','71','泾川县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('667','72','合水县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('668','72','华池县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('669','72','环县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('670','72','宁县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('671','72','庆城县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('672','72','西峰区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('673','72','镇原县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('674','72','正宁县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('675','73','甘谷县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('676','73','秦安县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('677','73','清水县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('678','73','秦州区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('679','73','麦积区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('680','73','武山县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('681','73','张家川','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('682','74','古浪县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('683','74','民勤县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('684','74','天祝','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('685','74','凉州区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('686','75','高台县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('687','75','临泽县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('688','75','民乐县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('689','75','山丹县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('690','75','肃南','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('691','75','甘州区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('692','76','从化市','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('693','76','天河区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('694','76','东山区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('695','76','白云区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('696','76','海珠区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('697','76','荔湾区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('698','76','越秀区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('699','76','黄埔区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('700','76','番禺区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('701','76','花都区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('702','76','增城区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('703','76','从化区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('704','76','市郊','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('705','77','福田区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('706','77','罗湖区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('707','77','南山区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('708','77','宝安区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('709','77','龙岗区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('710','77','盐田区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('711','78','湘桥区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('712','78','潮安县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('713','78','饶平县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('714','79','南城区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('715','79','东城区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('716','79','万江区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('717','79','莞城区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('718','79','石龙镇','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('719','79','虎门镇','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('720','79','麻涌镇','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('721','79','道滘镇','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('722','79','石碣镇','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('723','79','沙田镇','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('724','79','望牛墩镇','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('725','79','洪梅镇','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('726','79','茶山镇','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('727','79','寮步镇','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('728','79','大岭山镇','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('729','79','大朗镇','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('730','79','黄江镇','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('731','79','樟木头','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('732','79','凤岗镇','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('733','79','塘厦镇','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('734','79','谢岗镇','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('735','79','厚街镇','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('736','79','清溪镇','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('737','79','常平镇','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('738','79','桥头镇','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('739','79','横沥镇','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('740','79','东坑镇','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('741','79','企石镇','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('742','79','石排镇','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('743','79','长安镇','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('744','79','中堂镇','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('745','79','高埗镇','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('746','80','禅城区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('747','80','南海区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('748','80','顺德区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('749','80','三水区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('750','80','高明区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('751','81','东源县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('752','81','和平县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('753','81','源城区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('754','81','连平县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('755','81','龙川县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('756','81','紫金县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('757','82','惠阳区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('758','82','惠城区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('759','82','大亚湾','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('760','82','博罗县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('761','82','惠东县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('762','82','龙门县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('763','83','江海区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('764','83','蓬江区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('765','83','新会区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('766','83','台山市','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('767','83','开平市','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('768','83','鹤山市','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('769','83','恩平市','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('770','84','榕城区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('771','84','普宁市','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('772','84','揭东县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('773','84','揭西县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('774','84','惠来县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('775','85','茂南区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('776','85','茂港区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('777','85','高州市','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('778','85','化州市','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('779','85','信宜市','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('780','85','电白县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('781','86','梅县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('782','86','梅江区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('783','86','兴宁市','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('784','86','大埔县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('785','86','丰顺县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('786','86','五华县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('787','86','平远县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('788','86','蕉岭县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('789','87','清城区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('790','87','英德市','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('791','87','连州市','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('792','87','佛冈县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('793','87','阳山县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('794','87','清新县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('795','87','连山','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('796','87','连南','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('797','88','南澳县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('798','88','潮阳区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('799','88','澄海区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('800','88','龙湖区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('801','88','金平区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('802','88','濠江区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('803','88','潮南区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('804','89','城区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('805','89','陆丰市','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('806','89','海丰县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('807','89','陆河县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('808','90','曲江县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('809','90','浈江区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('810','90','武江区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('811','90','曲江区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('812','90','乐昌市','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('813','90','南雄市','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('814','90','始兴县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('815','90','仁化县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('816','90','翁源县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('817','90','新丰县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('818','90','乳源','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('819','91','江城区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('820','91','阳春市','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('821','91','阳西县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('822','91','阳东县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('823','92','云城区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('824','92','罗定市','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('825','92','新兴县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('826','92','郁南县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('827','92','云安县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('828','93','赤坎区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('829','93','霞山区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('830','93','坡头区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('831','93','麻章区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('832','93','廉江市','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('833','93','雷州市','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('834','93','吴川市','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('835','93','遂溪县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('836','93','徐闻县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('837','94','肇庆市','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('838','94','高要市','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('839','94','四会市','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('840','94','广宁县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('841','94','怀集县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('842','94','封开县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('843','94','德庆县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('844','95','石岐街道','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('845','95','东区街道','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('846','95','西区街道','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('847','95','环城街道','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('848','95','中山港街道','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('849','95','五桂山街道','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('850','96','香洲区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('851','96','斗门区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('852','96','金湾区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('853','97','邕宁区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('854','97','青秀区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('855','97','兴宁区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('856','97','良庆区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('857','97','西乡塘区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('858','97','江南区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('859','97','武鸣县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('860','97','隆安县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('861','97','马山县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('862','97','上林县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('863','97','宾阳县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('864','97','横县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('865','98','秀峰区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('866','98','叠彩区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('867','98','象山区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('868','98','七星区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('869','98','雁山区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('870','98','阳朔县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('871','98','临桂县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('872','98','灵川县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('873','98','全州县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('874','98','平乐县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('875','98','兴安县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('876','98','灌阳县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('877','98','荔浦县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('878','98','资源县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('879','98','永福县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('880','98','龙胜','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('881','98','恭城','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('882','99','右江区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('883','99','凌云县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('884','99','平果县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('885','99','西林县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('886','99','乐业县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('887','99','德保县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('888','99','田林县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('889','99','田阳县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('890','99','靖西县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('891','99','田东县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('892','99','那坡县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('893','99','隆林','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('894','100','海城区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('895','100','银海区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('896','100','铁山港区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('897','100','合浦县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('898','101','江州区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('899','101','凭祥市','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('900','101','宁明县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('901','101','扶绥县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('902','101','龙州县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('903','101','大新县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('904','101','天等县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('905','102','港口区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('906','102','防城区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('907','102','东兴市','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('908','102','上思县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('909','103','港北区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('910','103','港南区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('911','103','覃塘区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('912','103','桂平市','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('913','103','平南县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('914','104','金城江区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('915','104','宜州市','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('916','104','天峨县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('917','104','凤山县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('918','104','南丹县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('919','104','东兰县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('920','104','都安','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('921','104','罗城','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('922','104','巴马','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('923','104','环江','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('924','104','大化','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('925','105','八步区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('926','105','钟山县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('927','105','昭平县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('928','105','富川','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('929','106','兴宾区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('930','106','合山市','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('931','106','象州县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('932','106','武宣县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('933','106','忻城县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('934','106','金秀','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('935','107','城中区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('936','107','鱼峰区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('937','107','柳北区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('938','107','柳南区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('939','107','柳江县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('940','107','柳城县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('941','107','鹿寨县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('942','107','融安县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('943','107','融水','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('944','107','三江','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('945','108','钦南区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('946','108','钦北区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('947','108','灵山县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('948','108','浦北县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('949','109','万秀区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('950','109','蝶山区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('951','109','长洲区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('952','109','岑溪市','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('953','109','苍梧县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('954','109','藤县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('955','109','蒙山县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('956','110','玉州区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('957','110','北流市','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('958','110','容县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('959','110','陆川县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('960','110','博白县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('961','110','兴业县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('962','111','南明区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('963','111','云岩区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('964','111','花溪区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('965','111','乌当区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('966','111','白云区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('967','111','小河区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('968','111','金阳新区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('969','111','新天园区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('970','111','清镇市','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('971','111','开阳县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('972','111','修文县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('973','111','息烽县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('974','112','西秀区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('975','112','关岭','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('976','112','镇宁','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('977','112','紫云','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('978','112','平坝县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('979','112','普定县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('980','113','毕节市','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('981','113','大方县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('982','113','黔西县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('983','113','金沙县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('984','113','织金县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('985','113','纳雍县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('986','113','赫章县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('987','113','威宁','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('988','114','钟山区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('989','114','六枝特区','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('990','114','水城县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('991','114','盘县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('992','115','凯里市','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('993','115','黄平县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('994','115','施秉县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('995','115','三穗县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('996','115','镇远县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('997','115','岑巩县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('998','115','天柱县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('999','115','锦屏县','3','0');-- <fen> --
INSERT INTO `xt_region` VALUES ('1000','115','剑河县','3','0');-- <fen> --
