-- 清空表的:  --
DROP TABLE `xt_access`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `xt_address`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `xt_bonus`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `xt_bonus1`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `xt_bonushistory`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `xt_card`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `xt_cash`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `xt_cashhistory`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `xt_cashpp`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `xt_chongzhi`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `xt_cody`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `xt_cptype`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `xt_fck`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `xt_fck2`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `xt_fck_shop`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `xt_fee`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `xt_fenhong`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `xt_form`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `xt_form_class`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `xt_game`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `xt_gouwu`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `xt_gp`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `xt_gp_sell`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `xt_gupiao`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `xt_hgupiao`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `xt_history`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `xt_huikui`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `xt_img`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `xt_item`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `xt_jiadan`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `xt_msg`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `xt_news_a`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `xt_news_class`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `xt_peng`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `xt_plan`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `xt_product`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `xt_promo`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `xt_region`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `xt_remit`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `xt_shouru`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `xt_times`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `xt_times1`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `xt_tiqu`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `xt_ulevel`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `xt_xfhistory`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `xt_xiaof`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `xt_xml`;
-- <fen> --
-- 清空表的:  --
DROP TABLE `xt_zhuanj`;
-- <fen> --
